# Project Euler: Q29
# Find how many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100
numSet = set()
for i in range(2,101):
    for j in range(2,101):
        numSet.add(i ** j)
print(len(numSet))
